require "qt6"
require "crystal_mpd"
require "digest/sha1"
require "./mpd_ui/version"
require "./mpd_ui/settings"
require "./mpd_ui/decorators/song"
require "./mpd_ui/decorators/playlist_entry"
require "./mpd_ui/playback_state"
require "./mpd_ui/cover_art_service"
require "./mpd_ui/background_runner"
require "./mpd_ui/background_task"
require "./mpd_ui/dsp/spectrum_analyzer"
require "./mpd_ui/visualizer_service"
require "./mpd_ui/event_bridge"
require "./mpd_ui/format_helpers"
require "./mpd_ui/i18n"
require "./mpd_ui/item_roles"
require "./mpd_ui/two_line_item_delegate"
require "./mpd_ui/drag_context"
require "./mpd_ui/library_index"
require "./mpd_ui/app_actions"
require "./ext/mimemagic/src/mime_magic"
require "./mpd_ui/views/application_menu"
require "./mpd_ui/views/visualizer_widget"
require "./mpd_ui/views/player_header_view"
require "./mpd_ui/controllers/player_controller"
require "./mpd_ui/models/library_model"
require "./mpd_ui/models/playlists_model"
require "./mpd_ui/models/queue_model"
require "./mpd_ui/views/queue_view"
require "./mpd_ui/controllers/queue_controller"
require "./mpd_ui/controllers/playlist_controller"
require "./mpd_ui/views/library_view"
require "./mpd_ui/views/playlists_view"
require "./mpd_ui/views/app_layout_view"
require "./ext/lastfm/src/lastfm"
require "./ext/mpris/src/mpris"
require "./mpd_ui/adapters/mpris_adapter"
require "./mpd_ui/adapters/lastfm_adapter"
require "./mpd_ui/mpd_connection"
require "./mpd_ui/app/mpris"
require "./mpd_ui/app/lastfm"
require "./mpd_ui/app/settings_dialog"
require "./mpd_ui/app/outputs"
require "./mpd_ui/app/window_events"
require "./mpd_ui/app/tray"
require "./mpd_ui/app/queue"
require "./mpd_ui/app/database"
require "./mpd_ui/app/playlists"
require "./mpd_ui/app/about_dialog"
require "./mpd_ui/app/player"
require "./mpd_ui/app"

module MPDUI
  def self.run : Nil
    App.new.run
  end
end
